import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Provider from '@/provider'
import ReduxProvider from '@/store/provider'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className='h-full w-full'>
      <body className='h-full w-full'>
        <Provider>
          <ReduxProvider>
            {children}
          </ReduxProvider>
        </Provider>
      </body>
    </html>
  )
}
